### ISSUE TITLE
Whats the differences between this project and openHab?

### ISSUE THREAD

**Issue by naterh** [Neuronix2/IRISv2#17]
Both are java projects and openHab currently supports far more bindings and interfaces than this?  Why not merge the two?  I couldn't find much info on this project outside of whats in this git project and the name is somewhat misleading implying full Lowes Iris support w/ no zigbee etc.

**Comment by Neuronix2** [comment]
I have my own vision of the smart home project. In general, solved problems are similar, but substantial differences in architecture. Plus, the project is designed mostly for Russian-speaking users (including support for protocol Noolite, which does not exist anywhere except the CIS countries and Yandex speech synthesis)
